Feat/add viem
ethereum-optimism/optimism-starter pull request #44
Opened 2023-07-29 10:29 UTC by janndriessen

**Description**

* Adds viem 
* Updates wagmi and rainbowkit to latest versions
* Removes ethers

**Tests**

Changes didn't affect any tests.

**Additional context**

Left one `TODO` which I can't solve right now but not sure if it was due to upgrading wagmi or maybe changes in one of the optimism libraries.

**Metadata**

- Fixes #33

2023-07-29 10:31 UTC, janndriessen commented
Created in anticipation of the ETHGlobal Superhack next week where I'd love to use this template but with `viem`. If it's not merged maybe it could be an extra branch.

2023-07-29 15:28 UTC, roninjin10 requested changes
Amazing thank you so much for this pr and I'm excited to see you are planning to use it to hack with in an upcoming hackathon. Just 2 minor requests:
1. Screenshot the app running correctly
2. Let's update the README.md about how to get the wallet connect key

2023-07-29 15:28 UTC, roninjin10 commented on .env.example
> +# https://docs.walletconnect.com/2.0/web/web3wallet/installation#obtain-project-id
Let's add this to the Readme around the spot where we mention the etherscan key

2023-07-30 08:49 UTC, janndriessen commented
> Amazing thank you so much for this pr and I'm excited to see you are planning to use it to hack with in an upcoming hackathon. Just 2 minor requests:
> 
> 1. Screenshot the app running correctly
> 2. Let's update the README.md about how to get the wallet connect key

 🤝  Updated as requested.

2023-07-30 17:38 UTC, roninjin10 approved these changes

2023-07-30 17:39 UTC, merged